# Generated by Django 5.1.7 on 2025-04-13 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(related_name='trains', to='App.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
